### ISSUE TITLE
ddr-index broken: "ImportError: No module named envoy"

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-cmdln#114]
Trying to run `ddr-index` from command-line results in the following error (note that `ddr-transform` does not appear to be affected):

```
(ddrlocal) ddr@ishigura:/media/qnfs/kinkura/gold/ddr-densho-1000$ ddr-index
Traceback (most recent call last):
  File "/usr/local/bin/ddr-index", line 4, in <module>
    __import__('pkg_resources').run_script('ddr-cmdln==0.9.4-beta', 'ddr-index')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ddr_cmdln-0.9.4_beta-py2.7.egg/EGG-INFO/scripts/ddr-index", line 75, in <module>
    import envoy
ImportError: No module named envoy
(ddrlocal) ddr@ishigura:/media/qnfs/kinkura/gold/ddr-densho-1000$ ddr-transform
usage: ddr-transform [-h] [-f FILTER] [-M MODELS] [-t] [-R] [-C] [-u USER]
                     [-m MAIL]
                     collection
ddr-transform: error: too few arguments
```

This behavior is on standalone debian hosts `maunakea` and `ishigura` at HQ. Both are on:

`ddr-local`: `commit a8dd11b2cb5dc2315afb6b4aa596a5f6be09bc18`
`ddr-defs`: `commit 576ce8a3ee865db083a457fc2d0ad6345c2c8734`
 `ddr-cmdln`: `commit 00f731458c3c6030c4dcd3e9bedaff89bb62f21b`

Apps were installed used `make clean; make get-app; make install-app` with no errors. The command worked previously.

Also, `envoy` appears to be installed in the venv:

```
(ddrlocal) ddr@ishigura:/opt/ddr-local/ddr-cmdln$ pip install envoy
Requirement already satisfied: envoy in /opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages (0.0.3)
```

**Comment by GeoffFroh** [comment]
nevermind...it's the old version...
