### ISSUE TITLE
'Entity' object has no attribute 'rm_file_duplicates' in ddrimport

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#135]
```
$ ddrimport entity /media/sf_ddrshared/ddr-testing-40210-objects.csv /media/qnfs/kinkura/gold/ddr-testing-40210
...
2019-04-11 11:49:19,026 INFO     ------------------------------------------------------------------------
2019-04-11 11:49:19,026 INFO     batch import entity
2019-04-11 11:49:19,028 INFO     <git.Repo "/media/qnfs/kinkura/gold/ddr-testing-40210/.git">
2019-04-11 11:49:19,028 INFO     Reading /media/sf_ddrshared/ddr-testing-40210-objects.csv
2019-04-11 11:49:19,032 INFO     22 rows
2019-04-11 11:49:19,032 INFO     - - - - - - - - - - - - - - - - - - - - - - - -
2019-04-11 11:49:19,032 INFO     Importing
2019-04-11 11:49:19,033 INFO     1/22 - ddr-testing-40210-1
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/bin/ddrimport", line 14, in <module>
    load_entry_point('ddr-cmdln==0.9.4b0', 'console_scripts', 'ddrimport')()
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/cli/ddrimport.py", line 172, in entity
    dryrun=dryrun,
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/batch.py", line 554, in import_entities
    modified = entity.load_csv(rowd)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/entity.py", line 469, in load_csv
    self.rm_file_duplicates()
AttributeError: 'Entity' object has no attribute 'rm_file_duplicates'
```

**Comment by gjost** [comment]
This was a call to a function removed in the Entity delete commits.  Fixed in commit dc983af.
