### ISSUE TITLE
"'Entity' object has no attribute '_file_objects'"

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#136]
v280MA binary uploaded via webui. behavior replicated across multiple file types and sizes. from gitstatus updates message: 

Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/tasks/files.py", line 75, in add_file
    git_name, git_mail, agent
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/entity.py", line 606, in add_local_file
    self, src_path, role, data, git_name, git_mail, agent
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 446, in add_local_file
    entity._file_objects.append(file_)
AttributeError: 'Entity' object has no attribute '_file_objects'

[local.log](https://github.com/densho/ddr-cmdln/files/3070240/local.log)

**Comment by gjost** [comment]
This is addressed by changes made in the `141-entity-children` branch leading up to commit 509d57e.
