### ISSUE TITLE
uploading binaries fails: AttributeError("'module' object has no attribute 'add_local_file'",)

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-cmdln#158]
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/ddr-local/ddrlocal/webui/tasks/files.py", line 187, in file_add_local
    git_name, git_mail, agent=settings.AGENT
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/entity.py", line 662, in add_local_file
    return ingest.add_local_file(
AttributeError: 'module' object has no attribute 'add_local_file'

tested on PYK and SB vms (Dev 287-6) 

annoyingly this was working earlier in the day (managed to upload a single binary)

[celeryd.log](https://github.com/densho/ddr-cmdln/files/3374692/celeryd.log)

[local.log](https://github.com/densho/ddr-cmdln/files/3374693/local.log)

**Comment by pkikawa** [comment]
[ddr-testing-40277-1.log](https://github.com/densho/ddr-cmdln/files/3374701/ddr-testing-40277-1.log)

[ddr-testing-40277-1-1.log](https://github.com/densho/ddr-cmdln/files/3374702/ddr-testing-40277-1-1.log)

**Comment by GeoffFroh** [comment]
@gjost reports that this is an issue in `ddr-local`
