### ISSUE TITLE
Can't add new access files.

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#34]
Adding a new file works:

```
>>> from django.conf import settings
>>> from webui import identifier
>>> git_name = 'gjost'
>>> git_mail = 'gjost@densho.org'
>>> entity = identifier.Identifier('ddr-testing-345-1').object()
>>> src_path = '/tmp/bernie-sanders-socialism-scare.gif'
>>> role = 'mezzanine'
>>> data = {
...  'label': u'SOCIALISM!',
...  'path': u'/tmp/bernie-sanders-socialism-scare.gif',
...  'public': u'1',
...  'rights': u'cc',
...  'sort': 1,
... }
>>> agent = 'cmdln'
>>> file_,repo,log = entity.add_file(src_path, role, data, git_name, git_mail, agent)
>>> file_,repo,log = entity.add_file_commit(file_, repo, log, git_name, git_mail, agent)
>>> result = file_.post_json(settings.DOCSTORE_HOSTS, settings.DOCSTORE_INDEX)
No handlers could be found for logger "elasticsearch.trace"
```

But adding a new access file does not:

```
>>> from django.conf import settings
>>> from webui import identifier
>>> git_name = 'gjost'
>>> git_mail = 'gjost@densho.org'
>>> entity = identifier.Identifier('ddr-testing-345-1').object()
>>> ddrfile = identifier.Identifier('ddr-testing-345-1-master-77ec5e4008').object()
>>> src_path = u'files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.gif'
>>> agent = 'cmdln'
>>> file_,repo,log = entity.add_access(ddrfile, git_name, git_mail, agent)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    file_,repo,log = entity.add_access(ddrfile, git_name, git_mail, agent)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/__init__.py", line 1252, in add_access
    return ingest.add_access(self, ddrfile, git_name, git_mail, agent='')
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 542, in add_access
    repo = stage_files(entity, git_files, annex_files, new_files, log, show_staged=show_staged)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 283, in stage_files
    log.crash('Add file aborted, see log file for details: %s' % log.logpath)
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 46, in crash
    raise Exception(msg)
Exception: Add file aborted, see log file for details: /var/log/ddr/addfile/ddr-testing-345/ddr-testing-345-1.log
```

The operation fails leaving `FILE.json` modified and staged but not committed.

Here's the addfile.log

```
[2016-06-17T11:36:20.547080] ok - ------------------------------------------------------------------------
[2016-06-17T11:36:20.547210] ok - DDR.models.Entity.add_access: START
[2016-06-17T11:36:20.547271] ok - entity: ddr-testing-345-1
[2016-06-17T11:36:20.547461] ok - ddrfile: <webui.models.DDRFile 'ddr-testing-345-1-master-77ec5e4008'>
[2016-06-17T11:36:20.547513] ok - Checking files/dirs
[2016-06-17T11:36:20.547567] ok - check dir /var/www/media/ddr/ddr-testing-345/files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.gif (| src_path)
[2016-06-17T11:36:20.547669] ok - Identifier
[2016-06-17T11:36:20.547715] ok - | file_id ddr-testing-345-1-master-77ec5e4008
[2016-06-17T11:36:20.547756] ok - | basepath /var/www/media/ddr
[2016-06-17T11:36:20.548498] ok - | identifier <DDR.identifier.Identifier file:ddr-testing-345-1-master-77ec5e4008>
[2016-06-17T11:36:20.549069] ok - Checking files/dirs
[2016-06-17T11:36:20.549172] ok - check dir /var/www/media/ddr/tmp/file-add/ddr-testing-345/ddr-testing-345-1 (| tmp_dir)
[2016-06-17T11:36:20.549260] ok - check dir /var/www/media/ddr/ddr-testing-345/files/ddr-testing-345-1/files (| dest_dir)
[2016-06-17T11:36:20.549366] ok - Making access file
[2016-06-17T11:36:20.549451] ok - | /var/www/media/ddr/tmp/file-add/ddr-testing-345/ddr-testing-345-1/ddr-testing-345-1-master-77ec5e4008-a.jpg
[2016-06-17T11:36:20.590559] not ok - Traceback (most recent call last):
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/ingest.py", line 155, in make_access_file
    geometry=config.ACCESS_FILE_GEOMETRY
  File "/usr/local/src/env/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/imaging.py", line 117, in thumbnail
    out = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'convert /var/www/media/ddr/ddr-testing-345/files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.gif[0] -resize '1024x1024>' /var/www/media/ddr/tmp/file-add/ddr-testing-345/ddr-testing-345-1/ddr-testing-345-1-master-77ec5e4008-a.jpg' returned non-zero exit status 1
[2016-06-17T11:36:20.590728] ok - File object
[2016-06-17T11:36:20.590851] ok - | file_ <webui.models.DDRFile 'ddr-testing-345-1-master-77ec5e4008'>
[2016-06-17T11:36:20.590943] ok - Writing object metadata
[2016-06-17T11:36:20.591039] ok - | /var/www/media/ddr/tmp/file-add/ddr-testing-345/ddr-testing-345-1/ddr-testing-345-1-master-77ec5e4008.json
[2016-06-17T11:36:20.591940] ok - Moving files to dest_dir
[2016-06-17T11:36:20.591998] ok - | all files moved
[2016-06-17T11:36:20.592037] ok - Moving file .json to dest_dir
[2016-06-17T11:36:20.592125] ok - | mv /var/www/media/ddr/tmp/file-add/ddr-testing-345/ddr-testing-345-1/ddr-testing-345-1-master-77ec5e4008.json /var/www/media/ddr/ddr-testing-345/files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.json
[2016-06-17T11:36:20.592397] ok - | all files moved
[2016-06-17T11:36:20.592529] ok - Staging files
[2016-06-17T11:36:20.593645] ok - | repo <git.Repo "/var/www/media/ddr/ddr-testing-345/.git">
[2016-06-17T11:36:20.603926] ok - | 2 files to stage:
[2016-06-17T11:36:20.603996] ok - |   files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.json
[2016-06-17T11:36:20.604033] ok - |   files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008-a.jpg
[2016-06-17T11:36:20.604087] ok - git stage
[2016-06-17T11:36:20.610856] ok - annex stage
[2016-06-17T11:36:20.630233] ok - ok
[2016-06-17T11:36:20.636601] ok - | 1 files staged:
[2016-06-17T11:36:20.636658] ok - show_staged True
[2016-06-17T11:36:20.636684] ok - |   files/ddr-testing-345-1/files/ddr-testing-345-1-master-77ec5e4008.json
[2016-06-17T11:36:20.636721] not ok - 1 new files staged (should be 2)
[2016-06-17T11:36:20.636743] not ok - File staging aborted. Cleaning up
[2016-06-17T11:36:20.636774] not ok - finished cleanup. good luck...
[2016-06-17T11:36:20.636812] not ok - Add file aborted, see log file for details: /var/log/ddr/addfile/ddr-testing-345/ddr-testing-345-1.log
```

`ddr-local: 5bf6e4e794`
`ddr-cmdln: cce0071757`

**Comment by gjost** [comment]
Must have been fixed bc it's working now.
