### ISSUE TITLE
ddr-transform is broken

### ISSUE THREAD

**Issue by gjost** [densho/ddr-cmdln#55]

**Comment by pkikawa** [comment]
2018-03-21 09:34:30,891 INFO     0/487 /media/qnfs/kinkura/temp/rainerworkdir/ddr-densho-34/collection.json
2018-03-21 09:34:31,003 INFO          record_created: 2013-10-25 16:15:27-07:00 -> 2013-10-25 16:15:27-07:00
2018-03-21 09:34:31,489 INFO     1/487 /media/qnfs/kinkura/temp/rainerworkdir/ddr-densho-34/files/ddr-densho-34-110/entity.json
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/bin/ddr-transform", line 7, in <module>
    __import__('pkg_resources').run_script('ddr-cmdln==0.9.4b0', 'ddr-transform')
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 765, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1545, in run_script
    exec(code, namespace, namespace)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 149, in <module>
    main()
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 144, in main
    mail=args.mail,
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 88, in transform
    after = vocab.repair_topicdata(o.topics)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/vocab.py", line 651, in repair_topicdata
    for term in get_vocabs(config.VOCAB_TERMS_URL, 'topics')['terms']
NameError: global name 'get_vocabs' is not defined

**Comment by gjost** [comment]
@pkikawa what command were you running that led to the above error?

**Comment by gjost** [comment]
Never mind, the error presented when I used the `--topics` flag

**Comment by pkikawa** [comment]
2018-03-23 13:28:13,397 INFO     73/955 /media/qnfs/kinkura/temp/rainerworkdir/ddr-densho-330/files/ddr-densho-330-34/entity.json
2018-03-23 13:28:13,512 INFO          record_created: <built-in method now of type object at 0x9637c0> -> 2017-03-14 15:03:33-07:00
Traceback (most recent call last):
  File "/opt/ddr-local/venv/ddrlocal/bin/ddr-transform", line 7, in <module>
    __import__('pkg_resources').run_script('ddr-cmdln==0.9.4b0', 'ddr-transform')
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 149, in <module>
    main()
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 144, in main
    mail=args.mail,
  File "/opt/ddr-local/venv/ddrlocal/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/EGG-INFO/scripts/ddr-transform", line 99, in transform
    o.write_json()
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/__init__.py", line 1704, in write_json
    self.dump_json(doc_metadata=True, obj_metadata=obj_metadata),
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/__init__.py", line 1682, in dump_json
    template=template,)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/models/__init__.py", line 354, in dump_json
    getattr(obj, fieldname)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/modules.py", line 112, in function
    value = function(value)
  File "/opt/ddr-local/ddr-defs/repo_models/entity.py", line 1093, in jsondump_record_lastmod
    def jsondump_record_lastmod(data): return converters.datetime_to_text(data)
  File "/opt/ddr-local/venv/ddrlocal/local/lib/python2.7/site-packages/ddr_cmdln-0.9.4b0-py2.7.egg/DDR/converters.py", line 129, in datetime_to_text
    raise Exception('Cannot strformat "%s": not a datetime.' % data)
Exception: Cannot strformat "<built-in method now of type object at 0x9637c0>": not a datetime.

**Comment by gjost** [comment]
Again, please include the command you typed to produce the above error.

**Comment by gjost** [comment]
Looks like objects where transform works don't have timezone in record_created, whereas ddr-densho-330-34 does.

**Comment by gjost** [comment]
This is technically a different problem from the one reported above.  Please see https://github.com/densho/ddr-cmdln/issues/65
